version: '3.7'

services:
  db:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    image: echo-db-image
    container_name: echo-db-container
    ports:
      - '3306:3306'
    volumes:
      - echo-mysql-data:/var/lib/mysql
      - ./docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env

  golang:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: echo-api-image
    container_name: echo-api-container
    ports:
      - '8020:8020'
    volumes:
      - $PWD:/go/src/app
    depends_on:
      - db
    tty: true

  proxy:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    image: echo-proxy-image
    container_name: echo-proxy-container
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - golang

volumes:
  echo-mysql-data:
